Bd 38 스케줄 추가 UI 구현
DeveloperAcademy-POSTECH/MacC-Team-Bremen-DD pull request #16
Opened 2022-10-24 02:49 UTC by jayden000106

# 프로젝트 이미지 
(수정 및 구현 사항에 대한 간략한 캡쳐)
|시뮬레이터 캡쳐|피그마 파일|
|---|---|
|<img src="https://user-images.githubusercontent.com/103025692/197438837-fc09f0be-cdbd-4789-b425-d2704f5c71b3.png" width="276" />|<img width="276" alt="image" src="https://user-images.githubusercontent.com/103025692/197438878-1916ac0b-0360-488a-a3e2-19dbe1e053a7.png"/>|

## 세부 사항
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 스케줄 추가 UI만 구현했습니다.
- 근무지 선택 부분은 Custom Toggle로 구현했습니다.
- 나머지 필요한 부분은 TODO로 남겼습니다!

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점 및 공유할 내용)
- ForEach에 경고가 뜨는 부분을 어떻게 수정할까요... 리뷰가 필요합니다!
- 나머지 컴포넌트가 들어간 다음에 수정하도록 하겠습니다.
 
## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge)
- [x]  필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x]  코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x]  제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x]  본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-10-24 13:46 UTC, song-cool requested changes
열심히 작업중이시군요! 화이팅!!

2022-10-24 13:46 UTC, song-cool commented on Rlog/View/Schedule/ScheduleCreateView.swift
> +    @State var reason = ""
사유를 뷰모델에 안 넣은 이유가 있나요?

2022-10-24 13:46 UTC, song-cool commented on Rlog/View/Schedule/ScheduleCreateView.swift
> +        }
네비게이션이 연결될것같은데 이 부분을 미리 그려두시면 머지 된 이후에 조금 더 빠르게 연결작업을 할 수 있을것같아요!

2022-10-24 13:46 UTC, song-cool commented on Rlog/View/Schedule/ScheduleCreateView.swift
> +        @Binding var bindings: [Bool]
bindings를 조금 더 명시적으로 적으면 어떨까요? workspaceFlags를 받아오는데 이를 직접 사용하거나 tags를 쓸 수도 있을것같아요. 혹은 이부분도 [bool] 이니까 tagOptionList / flagOptionList 같은건 어떨까요?

2022-10-24 13:46 UTC, song-cool commented on Rlog/View/Schedule/ScheduleCreateView.swift
> +                    .keyboardType(.numberPad)
Text(":")가 빠졌습니다!

2022-10-24 13:57 UTC, song-cool commented
foreach 경고부분이 저는 안뜨는데요! 혹시 어떤부분인지 커멘트 남겨주실 수 있나요?

2022-10-24 15:42 UTC, jayden000106 commented on Rlog/View/Schedule/ScheduleCreateView.swift
> +        @Binding var bindings: [Bool]
변수명까지 추천해주셔서 감사합니다!
변수 네이밍 가이드에 따라서 flagOptions는 어떨까요...?

2022-10-24 15:43 UTC, jayden000106 commented on Rlog/View/Schedule/ScheduleCreateView.swift
> +    @State var reason = ""
빼먹었습니다...ㅎㅎ;;
수정 완료했습니다:)

2022-10-24 16:21 UTC, jayden000106 commented on Rlog/View/Schedule/ScheduleCreateView.swift
> +        }
Toolbar 작업 완료했습니다! 감사합니다:)

2022-10-24 16:39 UTC, insub4067 commented on Rlog/View/Schedule/ScheduleCreateView.swift
> +                        ForEach(viewModel.workspaces.indices, id: \.self) { index in
해당 코드는 추후에 코어데이터 연결하고 수정하도록 하겠습니다

2022-10-24 16:39 UTC, insub4067 commented on Rlog/ViewModel/Schedule/ScheduleCreateViewModel.swift
> +        if startHourText != "" && startMinuteText != "" && endHourText != "" && endMinuteText != "" {
isEmpty 가 좀더 readable 하지 않을까요?

2022-10-24 16:39 UTC, insub4067 commented on Rlog/View/Schedule/ScheduleCreateView.swift
> +        var label: String
근무지 선택을 위한 코드들인가요?
코어 데이터 연결후 수정하면 좋을거 같습니다!

2022-10-25 07:30 UTC, Junghoon-P commented on Rlog/View/Schedule/ScheduleCreateView.swift
> +        @Binding var bindings: [Bool]
flagOptions 좋은 것 같습니다.

2022-10-25 11:01 UTC, song-cool approved these changes

2022-10-25 11:04 UTC, jayden000106 commented on Rlog/View/Schedule/ScheduleCreateView.swift
> +        var label: String
[dd34ec0](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Bremen-DD/pull/16/commits/dd34ec08cefb4e643f6ddbc02d8796b2c9f51d1d) 수정 완료했습니다!

2022-10-25 11:04 UTC, jayden000106 commented on Rlog/ViewModel/Schedule/ScheduleCreateViewModel.swift
> +        if startHourText != "" && startMinuteText != "" && endHourText != "" && endMinuteText != "" {
[dd34ec0](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Bremen-DD/pull/16/commits/dd34ec08cefb4e643f6ddbc02d8796b2c9f51d1d) 수정 완료했습니다!

2022-10-25 11:05 UTC, jayden000106 commented on Rlog/ViewModel/Schedule/ScheduleCreateViewModel.swift
> +        if startHourText != "" && startMinuteText != "" && endHourText != "" && endMinuteText != "" {
연결 후 수정하겠습니다:)

2022-10-25 11:05 UTC, jayden000106 commented on Rlog/View/Schedule/ScheduleCreateView.swift
> +                        ForEach(viewModel.workspaces.indices, id: \.self) { index in
연결 후 수정하겠습니다:)

2022-10-25 11:06 UTC, Junghoon-P approved these changes
수고하셨습니다.

2022-10-25 11:06 UTC, merged