Bd 126 해당 요일에 맞는 알바 바인딩
DeveloperAcademy-POSTECH/MacC-Team-Bremen-DD pull request #72
Opened 2022-11-10 18:07 UTC by phainestha1

# 프로젝트 이미지 
https://user-images.githubusercontent.com/88080251/201172474-670adbf3-adf8-45dc-8702-a182a0ff0dd6.mov

<img width="503" alt="스크린샷 2022-11-11 오전 3 02 54" src="https://user-images.githubusercontent.com/88080251/201172554-46188606-2116-4d63-b75c-5c7e01794b61.png">

## 세부 사항
- 선택된 요일에 따라 해당하는 일정을 표시합니다.

## 기타 질문 및 특이 사항
- [이 PR](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Bremen-DD/pull/71) 을 먼저 머지해주세요
- Mockdata를 통한 로직 설계이므로 차후 CoreData와 연결 시 코드 변경이 진행될 예정입니다.
- 추가 근무, 연장 근무, 축소 근무 판단 로직이 같이 커밋 되었습니다 🥺
 
## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge)
- [x]  필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x]  코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x]  제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x]  본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-11-11 05:18 UTC, insub4067 requested changes

2022-11-11 05:18 UTC, insub4067 commented on Rlog/Extension/View+.swift
> +import Foundation
Foundation 👀

2022-11-11 05:18 UTC, insub4067 commented on Rlog/View/Components/BorderedTextField.swift
> +        .onChange(of: text) { newValue in
원래 뷰모델의 프로펄티 didSet 으로 로직을 옮겨주셔도 좋을거 같습니다

2022-11-11 05:18 UTC, insub4067 commented on Rlog/View/Schedule/ScheduleCell.swift
> +struct WorkspaceEntity: Identifiable {
앞으로 추가될 코어데이터랑 네이밍이 겹치니 바꿔주세요

2022-11-11 05:18 UTC, insub4067 commented on Rlog/View/Schedule/ScheduleCell.swift
> +struct ScheduleEntity {
앞으로 추가될 코어데이터랑 네이밍이 겹치니 바꿔주세요

2022-11-11 05:18 UTC, insub4067 commented on Rlog/View/Schedule/ScheduleCell.swift
> +struct WorkdayEntity {
앞으로 추가될 코어데이터랑 네이밍이 겹치니 바꿔주세요

2022-11-11 05:18 UTC, insub4067 commented on Rlog/View/Schedule/ScheduleListView.swift
> +    let weekDays: [String] = ["SUN", "MON", "TUE", "WED", "THU", "FRI", "SAT"]
enum 의 caseIterable 로 바꿔주시면 좋을거 같습니다

2022-11-11 05:18 UTC, insub4067 commented on Rlog/View/Schedule/ScheduleListView.swift
> +        let year = components.year! // ✅
강제 언래핑 👀

2022-11-11 05:18 UTC, insub4067 commented on Rlog/View/Schedule/ScheduleListView.swift
> +//                            withAnimation(.spring()) {
주석 처리된 이유가 뭔가요?

2022-11-11 05:18 UTC, insub4067 commented on Rlog/ViewModel/Schedule/ScheduleListViewModel.swift
>  import Foundation
Foundation 👀

2022-11-11 05:18 UTC, insub4067 commented on Rlog/ViewModel/Schedule/ScheduleListViewModel.swift
> +    @Published var currentDate = Date() {
강제 언래핑 👀

2022-11-11 05:18 UTC, insub4067 commented on Rlog/ViewModel/Schedule/ScheduleListViewModel.swift
> +        let year = components.year! // ✅
강제 언래핑 👀

2022-11-11 05:18 UTC, insub4067 commented on Rlog/ViewModel/Schedule/ScheduleListViewModel.swift
> +            focusDate = calendar.date(from: focusDateComponents)!
강제 언래핑 👀

2022-11-11 05:18 UTC, insub4067 commented on Rlog/ViewModel/Schedule/ScheduleListViewModel.swift
> +        var focusDate = calendar.date(from: focusDateComponents)!
강제 언래핑 👀

2022-11-11 05:18 UTC, insub4067 commented on Rlog/ViewModel/Schedule/ScheduleListViewModel.swift
> +            .range(of: .weekday, in: .weekOfYear, for: today)! // ✅
강제 언래핑 👀

2022-11-11 05:18 UTC, insub4067 commented on Rlog/ViewModel/Schedule/ScheduleListViewModel.swift
> +            let year = components.year! // ✅
강제 언래핑 👀

2022-11-11 05:18 UTC, insub4067 commented on Rlog/ViewModel/Schedule/ScheduleListViewModel.swift
> +        let date = components.day! // ✅
강제 언래핑 👀

2022-11-11 05:24 UTC, insub4067 commented on Rlog/ViewModel/Schedule/ScheduleListViewModel.swift
> +extension ScheduleListViewModel {
private extension 으로 private func 만 모아서 extension 안에 func 으로 넣어주셔도 읽기 편하고 좋을거 같습니다

2022-11-11 17:24 UTC, phainestha1 commented on Rlog/ViewModel/Schedule/ScheduleListViewModel.swift
> +            focusDate = calendar.date(from: focusDateComponents)!
[e1f1425](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Bremen-DD/pull/72/commits/e1f1425b32021b86ca56a069f41658b0e25b9597) 반영했습니다.

2022-11-11 17:25 UTC, phainestha1 commented on Rlog/ViewModel/Schedule/ScheduleListViewModel.swift
> +        var focusDate = calendar.date(from: focusDateComponents)!
[BD-124]([e1f1425](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Bremen-DD/pull/72/commits/e1f1425b32021b86ca56a069f41658b0e25b9597) 반영했습니다.

2022-11-11 17:26 UTC, phainestha1 commented on Rlog/ViewModel/Schedule/ScheduleListViewModel.swift
> +            .range(of: .weekday, in: .weekOfYear, for: today)! // ✅
[BD-124](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Bremen-DD/pull/70) 반영했습니다.

2022-11-11 17:26 UTC, phainestha1 commented on Rlog/ViewModel/Schedule/ScheduleListViewModel.swift
> +            let year = components.year! // ✅
[BD-124](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Bremen-DD/pull/70) 반영했습니다.

2022-11-11 17:26 UTC, phainestha1 commented on Rlog/ViewModel/Schedule/ScheduleListViewModel.swift
> +        let date = components.day! // ✅
[BD-124](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Bremen-DD/pull/70) 반영했습니다.

2022-11-11 17:28 UTC, phainestha1 commented on Rlog/View/Schedule/ScheduleCell.swift
> +struct WorkspaceEntity: Identifiable {
[b396798](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Bremen-DD/pull/72/commits/b39679807766784db6cbb737e56cfb1b58e06f7d) 반영했습니다.

2022-11-11 17:28 UTC, phainestha1 commented on Rlog/View/Schedule/ScheduleCell.swift
> +struct ScheduleEntity {
[b396798](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Bremen-DD/pull/72/commits/b39679807766784db6cbb737e56cfb1b58e06f7d) 반영했습니다.

2022-11-11 17:28 UTC, phainestha1 commented on Rlog/View/Schedule/ScheduleCell.swift
> +struct WorkdayEntity {
[b396798](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Bremen-DD/pull/72/commits/b39679807766784db6cbb737e56cfb1b58e06f7d) 반영했습니다.

2022-11-11 17:34 UTC, phainestha1 commented on Rlog/ViewModel/Schedule/ScheduleListViewModel.swift
> +extension ScheduleListViewModel {
[32bba08](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Bremen-DD/pull/72/commits/32bba08dee7db5af3a3b89ff87e8c1784acf4184) 반영했습니다.

2022-11-11 17:48 UTC, phainestha1 commented on Rlog/View/Schedule/ScheduleListView.swift
> +//                            withAnimation(.spring()) {
[5ee08c6](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Bremen-DD/pull/72/commits/5ee08c6b5058a39df53b326dc25ae3a443204590) 원래는 withAnimation을 통해 사용자가 날짜를 터치했을 때 애니메이션을 발생하는 것으로 구현했습니다. 
날짜의 포커스가 변할 때 스케쥴도 함께 변경되는데 이때 스케쥴의 애니메이션 매우 부자연스럽게 발생하더라고요. 그래서 withAnimation을 삭제하고 애니메이션이 발생하는 뷰에 transition을 사용했습니다.
이 때 해당 코드를 주석 처리했는데 삭제를 못했군요. 해당 주석 삭제하는 것으로  반영했습니다.

2022-11-12 16:38 UTC, Junghoon-P commented on Rlog/View/Components/BorderedTextField.swift
> +            .padding(.horizontal)
`EdgeInsets`을 활용한다면 한줄로 적을 수 있을 것 같아요!

2022-11-12 16:38 UTC, Junghoon-P commented on Rlog/View/Components/BorderedTextField.swift
> +        VStack {
초반에 스프린트전 코드 스타일 합의를 할때 Vstack을 적용할시 별도의
여백이 있는것이 아니라면 `spacing: 0`을 적어놓기로 했던 것 같습니다!
적용 부탁드립니다!

2022-11-13 10:56 UTC, phainestha1 commented on Rlog/View/Components/BorderedTextField.swift
> +        VStack {
[5ee08c6](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Bremen-DD/pull/72/commits/5ee08c6b5058a39df53b326dc25ae3a443204590) 반영했습니다.

2022-11-13 10:57 UTC, phainestha1 commented on Rlog/View/Components/BorderedTextField.swift
> +            .padding(.horizontal)
아직 합의되지 않은 코드 스타일 내용인 것 같습니다.
이전 커밋 내용을 참고하니 아직 EdgeInsets를 사용한 적이 없네요.
차후 리팩토링 과정에서 통일할 지 논의가 필요할 것 같습니다.
우선은 이전의 업무 방식을 유지하는 것이 어떨까요?

2022-11-13 16:14 UTC, song-cool commented
브랜치를 연달아 따게 되면서 이전 pr의 작업사항들이 함께 있군요!
저도 이렇게 잘 안해봐서 몰랐는데, 다음부터 이런 경우에 위에 적어주실때에 관련 코드의 위치나, 예시를 함께 적어서 이번 pr의 diff를 더 쉽게 찾을 수 있게 하이라이팅 해주시면 리뷰시간이 줄어들것같습니다!

2022-11-13 17:02 UTC, song-cool requested changes
주석에 이모지를 활용하니 엄청 주목도가 높아서 좋은것 같네요!

최대한 불필요한 리뷰는 안남기고자 했는데, 제가 남긴 리뷰중 혹시 다음 pr에서 구현 예정인 부분이 있다면 conversation을 닫고 어프루브 요청주세요!
추가로 스케줄이 '월' '수' '금'에 적용되어있는데 빌드시에 '화' '목' 토'로 적용되어있는데 로직에 실수가 있는듯합니다! indexing과 관련되어있을것 같아요!

2022-11-13 17:09 UTC, song-cool commented on Rlog/Model/Weekday.swift
> +    case sun = "SUN"
```suggestion
    case sun = "SUN"
    case mon = "MON"
    case tue = "TUE"
    case wed = "WED"
    case thu = "THU"
    case fri = "FRI"
    case sat = "SAT"
```
마지막에 언급한 요일 인덱싱 관련 이슈와
요일이 실재와 다르게 표시되는 이슈는 이렇게 수정하면 해결될것같습니다. CaseIterable이 작성 순서대로 리스트화해주는 이유때문인것같습니다.

PR본문중 스크린샷과 제가 빌드한 모습(하단 스크린샷)이 달라 보이는것을 생각해보면 코드가 옮겨지면서 누락된듯합니다!!

![image](https://user-images.githubusercontent.com/46256034/201534386-87092cab-ffd2-4041-85f9-73dc8f21ab16.png)

2022-11-14 00:29 UTC, insub4067 commented on Rlog/View/Components/BorderedTextField.swift
> +        .frame(maxWidth: .infinity, minHeight: 30, maxHeight: 30)
minWidth 지정 안해주어도 괜찮나요?

2022-11-14 00:29 UTC, insub4067 commented on Rlog/View/Components/BorderedTextField.swift
> +    var keyboardType: UIKeyboardType {
👍

2022-11-14 00:32 UTC, Junghoon-P commented on Rlog/View/Components/BorderedTextField.swift
> +            .padding(.horizontal)
스프린트 1차때 이미 코드리뷰를 통해 적용된 내용으로 기억합니다.
오늘 데일리 스탠드업때 논의하는게 어떨까요?

2022-11-14 03:19 UTC, phainestha1 commented on Rlog/View/Schedule/ScheduleCell.swift
> +    @ObservedObject var viewModel = ScheduleListViewModel()
임시용입니다.

2022-11-14 03:19 UTC, phainestha1 commented on Rlog/View/Schedule/ScheduleCell.swift
> +        }
임시용입니다.

2022-11-14 03:19 UTC, phainestha1 commented on Rlog/View/Schedule/ScheduleCell.swift
> +    // WorkspaceEntity
고려사항에 대한 주석입니다.

2022-11-14 03:20 UTC, phainestha1 commented on Rlog/View/Components/BorderedTextField.swift
> +        .frame(maxWidth: .infinity, minHeight: 30, maxHeight: 30)
padding, frame 등 디자인 디테일은 이번 PR에서는 제외하는 것으로 논의되었습니다.
@Junghoon-P

2022-11-14 03:21 UTC, phainestha1 commented on Rlog/Model/Weekday.swift
> +    case sun = "SUN"
[c7455b8](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Bremen-DD/pull/72/commits/c7455b89c011237f46e254a74b0042440198ea8a) 반영했습니다.

2022-11-14 03:24 UTC, phainestha1 commented on Rlog/Extension/DateFormatter+.swift
> +            case .weekday: return "E"
둘 다 동일한 의미이나 Swift의 Calendar에서 사용하는 표현을 선택했습니다.

2022-11-14 04:32 UTC, song-cool approved these changes
남겨주신 커멘트 확인했습니다! 고생하셨습니다!

2022-11-14 05:32 UTC, jayden000106 commented on Rlog/View/Schedule/ScheduleListView.swift
> +            .foregroundColor(.black)
이 부분도 제 PR(https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Bremen-DD/pull/74#discussion_r1020779551)에 남겨주신 리뷰처럼 컴포넌트로 수정될 예정인가요?

2022-11-14 05:35 UTC, jayden000106 commented on Rlog/View/Schedule/ScheduleListView.swift
> +            .foregroundColor(.black)
+ 폰트용 블랙이 따로 있어서 적용해주세면 좋을 것 같습니다

```suggestion
        HStack(spacing: 0) {
            Group {
                Button {
                } label: {
                    Image(systemName: "chevron.left")
                }
                Text(currentMonth)
                Button {
                } label: {
                    Image(systemName: "chevron.right")
                }
            }
            .font(.title)
            .foregroundColor(Color.fontBlack)
```

2022-11-14 05:41 UTC, phainestha1 commented on Rlog/View/Schedule/ScheduleListView.swift
> +            .foregroundColor(.black)
컴포넌트 작업 진행 예정입니다.
[93b187f](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Bremen-DD/pull/72/commits/93b187f9faed7c7e88f296c01463e4c5091c322d) 반영했습니다.

2022-11-14 05:42 UTC, jayden000106 approved these changes
수고하셨습니다~!

2022-11-14 05:46 UTC, insub4067 approved these changes

2022-11-14 05:47 UTC, merged