BD-134 : CoreData - Entity 작성
DeveloperAcademy-POSTECH/MacC-Team-Bremen-DD pull request #73
Opened 2022-11-11 05:37 UTC by insub4067

# 프로젝트 이미지 
(수정 및 구현 사항에 대한 간략한 캡쳐)

## 세부 사항
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- WorkspaceEntity 작성
- ScheduleEntity 작성
- WorkdayEntity 작성

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점 및 공유할 내용)
-
-
 
## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge)
- [x]  필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x]  코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x]  제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x]  본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-11-11 05:52 UTC, phainestha1 requested changes
테스크 분배 시 선정되었던 에픽, 테스크명 준수해주세요.

2022-11-11 06:35 UTC, insub4067 commented
> 테스크 분배 시 선정되었던 에픽, 테스크명 준수해주세요.

준수되지 않은 부분 수정됐습니다
감사합니다

2022-11-11 08:15 UTC, song-cool approved these changes
메모관련 변경사항까지 잘 적용해주셨군요! 고생하셨습니다!

2022-11-11 15:34 UTC, phainestha1 commented on Rlog/CoreData/Model/WorkdayEntity+CoreDataProperties.swift
> +    @NSManaged public var memo: String?
구두 상으로 옵셔널 적용 여부를 논의했었는데,
우선은 근무 일정 추가/수정 로직에도 똑같이 옵셔널로 진행하겠습니다.

2022-11-11 15:37 UTC, phainestha1 approved these changes
이전 PR에서는 @unnnyong 께서 해당 코드들의 테스트 결과를 요청하셨던 걸로 기억나는데요.
혹여 지금의 경우도 그러할 지 궁금하네요!
우선 어프루브 진행하겠습니다!

2022-11-12 16:26 UTC, Junghoon-P approved these changes

2022-11-14 05:11 UTC, jayden000106 approved these changes
수고하셨습니다!

2022-11-14 05:20 UTC, merged